name: "Estrutura de diretórios e arquivos"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  demonstrando-estrutura:
    name: "Demonstrar estrutura básica"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Mostrar estrutura .github/workflows
        run: |
          echo "== Estrutura de diretorios e arquivos .github/worflows == "
          ls -la .github/workflows
          echo ""
          echo " Total de workflows: $(ls -l .github/worflows | wc -l) "

      - name: Elementos obrigatórios
        run: |
        echo    